runtime: python311
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker -b :$PORT backend.main:app

instance_class: F2

env_variables:
  DATABASE_URL: 'sqlite:///backend/db.sqlite'
  ENCRYPTION_KEY: 'MGlASYbvHhTb35gbGlTqqxTR9PZ5ernwF43QDz4Y0c0='
  APP_ENV: 'dev'
  APP_PORT: '8080'
  ADMIN_TOKEN: 'a7e183f180d1d28d4566a8965d0c055d52919a1fce7a0322'
  BASE_RPC_URL: 'https://mainnet.base.org'
  ETH_PRIVATE_KEY: '0x1b340507f5835567e129f4a39d469d99007d61f05db3ea7687cd0dec5ffc4b2f'
  REGISTRY_ADDR: '0x92b3d8295935D6CA6591c8B4F00d85AcA2314616'
  REGISTRY_CONTRACT_ADDRESS: '0x92b3d8295935D6CA6591c8B4F00d85AcA2314616'
  START_BLOCK: '34285640'
  OLD_CDP_JWT_ALG: 'Ed25519'
  CDP_KEY_ID: 'organizations/2666392e-1ecd-4a13-b0d1-5d96fe2770fa/apiKeys/aeef1fe4-2c84-42f0-ae65-c5edb964a2e4'
  CDP_JWT_NO_URIS: '1'
  CDP_KEY_NAME: 'conf_0pi'
  OLD_CDP_KEY_NAME: 'organizations/2666392e-1ecd-4a13-b0d1-5d96fe2770fa/apiKeys/5765df1d-b935-42ef-88f1-6e21b69de753'
  OLD_CDP_KEY_SECRET: 'MHcCAQEEIDrm1bb2gIZa3dhDGCHt/RMkzfdRg7YLst38qSKk7pIJoAoGCCqGSM49AwEHoUQDQgAEiCgSdmGsMpAHjDCgEBzPFU3iMZSnFG/troylpiw0gLBJeThWsQS+Pd5JXAhrI3xy4c8fH5xni/7Rdjzy3xsjGA=='
  CDP_NETWORK: 'base'
  OLD_SUBGRAPH_URL: 'https://api.studio.thegraph.com/query/118860/0-pi/v0.0.1'
  SUBGRAPH_URL: 'https://gateway.thegraph.com/api/subgraphs/id/ATaqRtwktwWwQe5n1Znx1uiPEhVoFcW74RBZqjx2918n'
  SUBGRAPH_EXPLORER_BASE: 'https://thegraph.com/studio/subgraph/0-pi'
  BASE_SCAN_BASE: 'https://basescan.org/tx/'
  SUBGRAPH_API_KEY: '1bcb285471c8898d08ca9ee304d5b4ce'
  SUBGRAPH_ID: 'ATaqRtwktwWwQe5n1Znx1uiPEhVoFcW74RBZqjx2918n'
  ETHEREUM_RPC_URL: 'https://rpc.payload.de'
  X402_NETWORK: 'base'
  DEMO_URL: 'localhost:8000/x402/openai/v1/models'
  USDC_CONTRACT_ADDRESS: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
